### ISSUE TITLE
error: dst ref refs/heads/master receives from more than one src

### ISSUE THREAD

**Issue by daolou** [ibnesayeed/repo-attrs#3]
second use, get  git error: dst ref refs/heads/main receives from more than one src

```sh
git push --follow-tags origin main
error: dst ref refs/heads/master receives from more than one src
error: failed to push some refs to 'gitosis@xxx.xx:xxx.git'
```

**Comment by ibnesayeed** [comment]
Is this error related to this repo? If so, how?

**Comment by daolou** [comment]
> Is this error related to this repo? If so, how?

maybe it is `create-release`

**Comment by daolou** [comment]
https://github.com/actions/create-release/issues/13
